# Generated by Django 2.0.1 on 2019-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_send', models.CharField(max_length=50)),
                ('user_receive', models.CharField(max_length=50)),
                ('send_time', models.CharField(max_length=50)),
                ('receive_time', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('text_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField(max_length=50000)),
                ('path', models.CharField(max_length=50)),
                ('upload_time', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('img_path', models.CharField(max_length=100)),
                ('clicks', models.TextField()),
                ('alter_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('money', models.CharField(max_length=1000)),
                ('spend', models.CharField(max_length=1000)),
                ('admin', models.CharField(max_length=10)),
                ('register_time', models.CharField(max_length=100)),
                ('read_time', models.CharField(max_length=100)),
                ('last_reading', models.CharField(max_length=100)),
            ],
        ),
    ]
