# Generated by Django 2.0.1 on 2019-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='read',
            field=models.TextField(default='0'),
        ),
    ]
