# Generated by Django 2.0.1 on 2019-06-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190610_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='read',
            field=models.TextField(default=' / / /'),
        ),
    ]
