# Generated by Django 2.0.1 on 2019-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190611_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='clicks',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
